create table public.countries (
id bigint generated by default as identity not null,
code character varying not null,
name_cn character varying null,
region character varying null,
gdp bigint null,
visa_free_count integer null,
visa_on_arrival_count integer null,
evisa_count integer null,
banned_count integer null,
created_at timestamp without time zone null default now(),
updated_at timestamp with time zone null default now(),
constraint countries_pkey primary key (id),
constraint countries_code_key unique (code),
constraint countries_name_cn_key unique (name_cn)
) TABLESPACE pg_default;

create table public.passport_relationships (
  id bigint generated by default as identity not null,
  passport_code character varying not null,
  destination_code character varying not null,
  visa_type character varying not null,
  stay_duration character varying null,
  destination_region character varying null,
  created_at timestamp without time zone null default now(),
  constraint passport_relationships_pkey primary key (id),
  constraint passport_relationships_destination_code_fkey foreign KEY (destination_code) references countries (code)
) TABLESPACE pg_default;